export const ADD_PERSON = "ADD_PERSON"
export const DELETE_PERSON = "DELETE_PERSON"
export const UPDATE_PERSON = "UPDATE_PERSON"
export const GET_PERSON = "GET_PERSON"
export const GET_PEOPLE = "GET_PEOPLE"
export const SHOW_POPUP = "SHOW_POPUP"
export const HIDE_POPUP = "HIDE_POPUP"
